In [ ]:
# Practice : Creating a Mode with decision trees -  Part 1 : Melborune_housing data set

In [1]:
import pandas as pd

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

In [2]:
df = pd.read_csv("Melbourne_housing_FULL.csv")

In [3]:
df.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,34857.000000,2.724700e+04,34856.000000,34856.000000,26640.000000,26631.000000,26129.000000,23047.000000,13742.00000,15551.000000,26881.000000,26881.000000,34854.000000
mean,3.031012,1.050173e+06,11.184929,3116.062859,3.084647,1.624798,1.728845,593.598993,160.25640,1965.289885,-37.810634,145.001851,7572.888306
std,0.969933,6.414671e+05,6.788892,109.023903,0.980690,0.724212,1.010771,3398.841946,401.26706,37.328178,0.090279,0.120169,4428.090313
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1196.000000,-38.190430,144.423790,83.000000
25%,2.000000,6.350000e+05,6.400000,3051.000000,2.000000,1.000000,1.000000,224.000000,102.00000,1940.000000,-37.862950,144.933500,4385.000000
50%,3.000000,8.700000e+05,10.300000,3103.000000,3.000000,2.000000,2.000000,521.000000,136.00000,1970.000000,-37.807600,145.007800,6763.000000
75%,4.000000,1.295000e+06,14.000000,3156.000000,4.000000,2.000000,2.000000,670.000000,188.00000,2000.000000,-37.754100,145.071900,10412.000000
max,16.000000,1.120000e+07,48.100000,3978.000000,30.000000,12.000000,26.000000,433014.000000,44515.00000,2106.000000,-37.390200,145.526350,21650.000000

In [4]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [5]:
df.head(7)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0
5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra City Council,-37.7969,144.9969,Northern Metropolitan,4019.0
6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra City Council,-37.8072,144.9941,Northern Metropolitan,4019.0

In [6]:
df=df.dropna(axis=0)

In [7]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0
6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra City Council,-37.8072,144.9941,Northern Metropolitan,4019.0
11,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,7/05/2016,2.5,3067.0,...,2.0,0.0,245.0,210.0,1910.0,Yarra City Council,-37.8024,144.9993,Northern Metropolitan,4019.0
14,Abbotsford,98 Charles St,2,h,1636000.0,S,Nelson,8/10/2016,2.5,3067.0,...,1.0,2.0,256.0,107.0,1890.0,Yarra City Council,-37.8060,144.9954,Northern Metropolitan,4019.0

In [8]:
y = df.Price

In [9]:
y

2        1035000.0
4        1465000.0
6        1600000.0
11       1876000.0
14       1636000.0
           ...
34847     500000.0
34849     570000.0
34853     888000.0
34854     705000.0
34856    1020000.0
Name: Price, Length: 8887, dtype: float64

In [10]:
melbourne_features = ['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']

In [13]:
x = df[melbourne_features]

In [14]:
x

       Rooms  Bathroom  Landsize  Lattitude  Longtitude
2          2       1.0     156.0  -37.80790   144.99340
4          3       2.0     134.0  -37.80930   144.99440
6          4       1.0     120.0  -37.80720   144.99410
11         3       2.0     245.0  -37.80240   144.99930
14         2       1.0     256.0  -37.80600   144.99540
...      ...       ...       ...        ...         ...
34847      3       2.0     383.0  -37.61940   145.03951
34849      3       2.0     404.0  -37.61031   145.03393
34853      2       2.0      98.0  -37.81551   144.88826
34854      2       1.0     220.0  -37.82286   144.87856
34856      2       1.0     250.0  -37.81810   144.89351

[8887 rows x 5 columns]

In [19]:
df.head()

    Rooms  Bathroom  Landsize  Lattitude  Longtitude
2       2       1.0     156.0   -37.8079    144.9934
4       3       2.0     134.0   -37.8093    144.9944
6       4       1.0     120.0   -37.8072    144.9941
11      3       2.0     245.0   -37.8024    144.9993
14      2       1.0     256.0   -37.8060    144.9954

In [15]:
x.describe()

             Rooms     Bathroom      Landsize    Lattitude   Longtitude
count  8887.000000  8887.000000   8887.000000  8887.000000  8887.000000
mean      3.098909     1.646450    523.480365   -37.804501   144.991393
std       0.963786     0.721611   1061.324228     0.090549     0.118919
min       1.000000     1.000000      0.000000   -38.174360   144.423790
25%       2.000000     1.000000    212.000000   -37.858560   144.920000
50%       3.000000     2.000000    478.000000   -37.798700   144.998500
75%       4.000000     2.000000    652.000000   -37.748945   145.064560
max      12.000000     9.000000  42800.000000   -37.407200   145.526350

In [16]:
from sklearn.tree import DecisionTreeRegressor
melbourne_model = DecisionTreeRegressor(random_state=1)

# Fit model
melbourne_model.fit(x, y)
# Specifying a number for random_state ensures you get the same results in each run.
#This is considered a good practice. You use any number, and model quality won't depend meaningfully on exactly what value you choose.

DecisionTreeRegressor(random_state=1)

In [17]:
print("Making predictions for the following 5 houses:")
print(x.head())
print("The predictions are")
print(melbourne_model.predict(x.head()))

Making predictions for the following 5 houses:
    Rooms  Bathroom  Landsize  Lattitude  Longtitude
2       2       1.0     156.0   -37.8079    144.9934
4       3       2.0     134.0   -37.8093    144.9944
6       4       1.0     120.0   -37.8072    144.9941
11      3       2.0     245.0   -37.8024    144.9993
14      2       1.0     256.0   -37.8060    144.9954
The predictions are
[1035000. 1465000. 1600000. 1876000. 1636000.]

In [18]:
# Part 2  - tips.csv
tips_data = pd.read_csv('tips.csv')
tips_data.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [20]:
# describing the data frame
tips_data.describe()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [23]:
# Removing rows with missing values
tips_data = tips_data.dropna(axis=0)

In [24]:
#Specify Prediction Target
y = tips_data.tip
y

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [31]:
# changing female and male to zero and one
tips_data['sex'].replace(['Female','Male'],[0,1],inplace = True)
tips_data

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,0,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,1,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,1,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,1,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,0,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,1,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,0,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,1,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,1,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,0,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [32]:
#Predicting Feautures
feature_names =['total_bill','sex','size','price_per_person']
X = tips_data[feature_names]
X

     total_bill  sex  size  price_per_person
0         16.99    0     2              8.49
1         10.34    1     3              3.45
2         21.01    1     3              7.00
3         23.68    1     2             11.84
4         24.59    0     4              6.15
..          ...  ...   ...               ...
239       29.03    1     3              9.68
240       27.18    0     2             13.59
241       22.67    1     2             11.34
242       17.82    1     2              8.91
243       18.78    0     2              9.39

[244 rows x 4 columns]

In [34]:
from sklearn.tree import DecisionTreeRegressor
tips_model = DecisionTreeRegressor(random_state=1)

In [35]:
# Fitting  the model
tips_model.fit(X,y)

DecisionTreeRegressor(random_state=1)

In [41]:
print("Making Prediction for the following 5 customers: ")
print(X.head())
print("Predicted tips for the 5 customers: ")
print(tips_model.predict(X.head()))

Making Prediction for the following 5 customers:
   total_bill  sex  size  price_per_person
0       16.99    0     2              8.49
1       10.34    1     3              3.45
2       21.01    1     3              7.00
3       23.68    1     2             11.84
4       24.59    0     4              6.15
Predicted tips for the 5 customers:
[1.01 1.66 3.5  3.31 3.61]

In [42]:
#
tips_data.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,0,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,1,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,1,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,1,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,0,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251